export const resources = [
	'account',
	'fibu_account_group',	
	'article',	
	'article_type',	 
	'bank_account',	 
	'kb_bill'	,
	'calendar',	
	'client'	,
	'client_service',	 
	'statistic'	,
	'communication_kind',	
	'company_profile'	,
	'contact'	,
	'contact_branch',	
	'contact_group'	,
	'contact_relation',	
	'contact_type'	,
	'country'	,
	'currency',	
	'expense'	,
	'kb_invoice',	
	'kb_reminder',	 
	'kb_offer'	,
	'kb_order'	,
	'kb_delivery'	,
	'language'	,
	'lead'	,
	'lead_source',	 
	'lead_status'	, 
	'logopaper'	,
	'time_tracking',	
	'monitoring_status',	 
	'note'	,
	'payment_type',	 
	'pr_project'	,
	'pr_state'	 ,
	'pr_project_type',	 
	'salutation'	,
	'stock'	 ,
	'stock_place',	 
	'task'	,
	'tax'	,
	'title',	
	'todo_priority',	 
	'todo_status'	 ,
	'unit'	,
	'user'	
];